/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE for Visual Studio Code Extension
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2025 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include "app_tasks.h"
#include "board_clock.h"
#include "can.h"
#include "FreeRTOS.h"
#include "frc_can.h"
#include "imu.h"
#include "io.h"
#include "stm32f4xx_hal.h"
#include "task.h"
#include "usb_device.h"

int main(void)
{
    HAL_Init();
    if (board_clock_config() != HAL_OK) {
        for (;;) {}
    }

    io_init();
    frc_can_config_init();
    MX_USB_DEVICE_Init();

    if (!can_init(BOARD_APB1_CLOCK_HZ, CAN_FRC_BIT_RATE_HZ)) {
        for (;;) {}
    }
    if (!imu_init(BOARD_APB2_TIMER_CLOCK_HZ)) {
        for (;;) {}
    }
    if (!app_tasks_start()) {
        for (;;) {}
    }

    vTaskStartScheduler();
    for (;;) {}
}
