#ifndef BOARD_IO_H
#define BOARD_IO_H

#include <stdint.h>

/*
 * RoboMaster Development Board Type C pin map, taken from the Chinese user
 * manual's "network name to IO" table (pages 17-18).  Names follow the label
 * printed on the board or connector, not arbitrary MCU naming.
 */
#define BOARD_GPIOA_BASE 0x40020000UL
#define BOARD_GPIOB_BASE 0x40020400UL
#define BOARD_GPIOC_BASE 0x40020800UL
#define BOARD_GPIOD_BASE 0x40020C00UL
#define BOARD_GPIOE_BASE 0x40021000UL
#define BOARD_GPIOF_BASE 0x40021400UL
#define BOARD_GPIOG_BASE 0x40021800UL
#define BOARD_GPIOH_BASE 0x40021C00UL
#define BOARD_GPIOI_BASE 0x40022000UL

typedef struct { uint32_t port; uint8_t pin; } board_pin_t;
#define BOARD_PIN_MASK(pin) (1UL << (pin))

/* RGB LED control nets: active high; all three outputs high = white on. */
#define BOARD_LED_BLUE_PORT BOARD_GPIOH_BASE
#define BOARD_LED_BLUE_PIN  10U
#define BOARD_LED_GREEN_PORT BOARD_GPIOH_BASE
#define BOARD_LED_GREEN_PIN  11U
#define BOARD_LED_RED_PORT BOARD_GPIOH_BASE
#define BOARD_LED_RED_PIN  12U

/* User controls and controlled power. */
#define BOARD_USER_BUTTON_PORT BOARD_GPIOA_BASE /* active low */
#define BOARD_USER_BUTTON_PIN  0U
#define BOARD_LASER_5V_ENABLE_PORT BOARD_GPIOC_BASE
#define BOARD_LASER_5V_ENABLE_PIN  8U
#define BOARD_BATTERY_VOLTAGE_ADC_PORT BOARD_GPIOF_BASE /* ADC3_IN8, 200k/22k divider */
#define BOARD_BATTERY_VOLTAGE_ADC_PIN  10U

/* CAN connectors: CAN1 is 2-pin, CAN2 is 4-pin. Both use AF9. */
#define BOARD_CAN1_RX_PORT BOARD_GPIOD_BASE
#define BOARD_CAN1_RX_PIN  0U
#define BOARD_CAN1_TX_PORT BOARD_GPIOD_BASE
#define BOARD_CAN1_TX_PIN  1U
#define BOARD_CAN2_RX_PORT BOARD_GPIOB_BASE
#define BOARD_CAN2_RX_PIN  5U
#define BOARD_CAN2_TX_PORT BOARD_GPIOB_BASE
#define BOARD_CAN2_TX_PIN  6U

/* UART connectors. Board silk names are misleading: UART1 = USART6. */
#define BOARD_UART1_USART6_TX_PORT BOARD_GPIOG_BASE /* 3-pin, referee power */
#define BOARD_UART1_USART6_TX_PIN  14U
#define BOARD_UART1_USART6_RX_PORT BOARD_GPIOG_BASE
#define BOARD_UART1_USART6_RX_PIN  9U
#define BOARD_UART2_USART1_TX_PORT BOARD_GPIOA_BASE /* 4-pin */
#define BOARD_UART2_USART1_TX_PIN  9U
#define BOARD_UART2_USART1_RX_PORT BOARD_GPIOB_BASE
#define BOARD_UART2_USART1_RX_PIN  7U

/* DJI DBUS receiver: inverter is on-board; use USART3 RX, 100 kbit/s, 8E1. */
#define BOARD_DBUS_USART3_RX_PORT BOARD_GPIOC_BASE
#define BOARD_DBUS_USART3_RX_PIN  11U

/* Servo/PWM connector, pins C1-C7. */
#define BOARD_PWM_1_PORT BOARD_GPIOE_BASE /* TIM1_CH1 */
#define BOARD_PWM_1_PIN  9U
#define BOARD_PWM_2_PORT BOARD_GPIOE_BASE /* TIM1_CH2 */
#define BOARD_PWM_2_PIN  11U
#define BOARD_PWM_3_PORT BOARD_GPIOE_BASE /* TIM1_CH3 */
#define BOARD_PWM_3_PIN  13U
#define BOARD_PWM_4_PORT BOARD_GPIOE_BASE /* TIM1_CH4 */
#define BOARD_PWM_4_PIN  14U
#define BOARD_PWM_5_PORT BOARD_GPIOC_BASE /* TIM8_CH1 */
#define BOARD_PWM_5_PIN  6U
#define BOARD_PWM_6_PORT BOARD_GPIOI_BASE /* TIM8_CH2 */
#define BOARD_PWM_6_PIN  6U
#define BOARD_PWM_7_PORT BOARD_GPIOI_BASE /* TIM8_CH3 */
#define BOARD_PWM_7_PIN  7U
#define BOARD_BUZZER_PORT BOARD_GPIOD_BASE /* TIM4_CH3 */
#define BOARD_BUZZER_PIN  14U

/* Configurable 8-pin I/O header. SPI2 and I2C2 alternatives conflict. */
#define BOARD_CONFIG_SPI2_CS_PORT BOARD_GPIOB_BASE
#define BOARD_CONFIG_SPI2_CS_PIN  12U
#define BOARD_CONFIG_SPI2_SCK_PORT BOARD_GPIOB_BASE
#define BOARD_CONFIG_SPI2_SCK_PIN  13U
#define BOARD_CONFIG_SPI2_MISO_PORT BOARD_GPIOB_BASE
#define BOARD_CONFIG_SPI2_MISO_PIN  14U
#define BOARD_CONFIG_SPI2_MOSI_PORT BOARD_GPIOB_BASE
#define BOARD_CONFIG_SPI2_MOSI_PIN  15U
#define BOARD_CONFIG_I2C2_SCL_PORT BOARD_GPIOF_BASE
#define BOARD_CONFIG_I2C2_SCL_PIN  1U
#define BOARD_CONFIG_I2C2_SDA_PORT BOARD_GPIOF_BASE
#define BOARD_CONFIG_I2C2_SDA_PIN  0U

/* Digital-camera 18-pin FPC connector. */
#define BOARD_CAMERA_I2C1_SCL_PORT BOARD_GPIOB_BASE
#define BOARD_CAMERA_I2C1_SCL_PIN  8U
#define BOARD_CAMERA_I2C1_SDA_PORT BOARD_GPIOB_BASE
#define BOARD_CAMERA_I2C1_SDA_PIN  9U
#define BOARD_CAMERA_PCLK_PORT BOARD_GPIOA_BASE
#define BOARD_CAMERA_PCLK_PIN  6U
#define BOARD_CAMERA_HREF_PORT BOARD_GPIOH_BASE
#define BOARD_CAMERA_HREF_PIN  8U
#define BOARD_CAMERA_VSYNC_PORT BOARD_GPIOI_BASE
#define BOARD_CAMERA_VSYNC_PIN  5U
#define BOARD_CAMERA_D0_PORT BOARD_GPIOH_BASE
#define BOARD_CAMERA_D0_PIN  9U
#define BOARD_CAMERA_D1_PORT BOARD_GPIOC_BASE
#define BOARD_CAMERA_D1_PIN  7U
#define BOARD_CAMERA_D2_PORT BOARD_GPIOE_BASE
#define BOARD_CAMERA_D2_PIN  0U
#define BOARD_CAMERA_D3_PORT BOARD_GPIOE_BASE
#define BOARD_CAMERA_D3_PIN  1U
#define BOARD_CAMERA_D4_PORT BOARD_GPIOE_BASE
#define BOARD_CAMERA_D4_PIN  4U
#define BOARD_CAMERA_D5_PORT BOARD_GPIOI_BASE
#define BOARD_CAMERA_D5_PIN  4U
#define BOARD_CAMERA_D6_PORT BOARD_GPIOE_BASE
#define BOARD_CAMERA_D6_PIN  5U
#define BOARD_CAMERA_D7_PORT BOARD_GPIOE_BASE
#define BOARD_CAMERA_D7_PIN  6U

/* On-board BMI088 IMU: SPI1 plus independent chip selects/interrupts. */
#define BOARD_IMU_SPI1_SCK_PORT BOARD_GPIOB_BASE
#define BOARD_IMU_SPI1_SCK_PIN  3U
#define BOARD_IMU_SPI1_MOSI_PORT BOARD_GPIOA_BASE
#define BOARD_IMU_SPI1_MOSI_PIN  7U
#define BOARD_IMU_SPI1_MISO_PORT BOARD_GPIOB_BASE
#define BOARD_IMU_SPI1_MISO_PIN  4U
#define BOARD_IMU_ACCEL_CS_PORT BOARD_GPIOA_BASE
#define BOARD_IMU_ACCEL_CS_PIN  4U
#define BOARD_IMU_GYRO_CS_PORT BOARD_GPIOB_BASE
#define BOARD_IMU_GYRO_CS_PIN  0U
#define BOARD_IMU_ACCEL_INT_PORT BOARD_GPIOC_BASE
#define BOARD_IMU_ACCEL_INT_PIN  4U
#define BOARD_IMU_GYRO_INT_PORT BOARD_GPIOC_BASE
#define BOARD_IMU_GYRO_INT_PIN  5U
#define BOARD_IMU_HEATER_PORT BOARD_GPIOF_BASE /* TIM10_CH1 */
#define BOARD_IMU_HEATER_PIN  6U

/* On-board IST8310 magnetometer: I2C3, address 0x0E. */
#define BOARD_MAG_I2C3_SCL_PORT BOARD_GPIOA_BASE
#define BOARD_MAG_I2C3_SCL_PIN  8U
#define BOARD_MAG_I2C3_SDA_PORT BOARD_GPIOC_BASE
#define BOARD_MAG_I2C3_SDA_PIN  9U
#define BOARD_MAG_RESET_PORT BOARD_GPIOG_BASE
#define BOARD_MAG_RESET_PIN  6U
#define BOARD_MAG_DATA_READY_PORT BOARD_GPIOG_BASE
#define BOARD_MAG_DATA_READY_PIN  3U

/* USB OTG FS and SWD debug signals. */
#define BOARD_USB_OTG_ID_PORT BOARD_GPIOA_BASE
#define BOARD_USB_OTG_ID_PIN  10U
#define BOARD_USB_DM_PORT BOARD_GPIOA_BASE
#define BOARD_USB_DM_PIN  11U
#define BOARD_USB_DP_PORT BOARD_GPIOA_BASE
#define BOARD_USB_DP_PIN  12U
#define BOARD_SWDIO_PORT BOARD_GPIOA_BASE
#define BOARD_SWDIO_PIN  13U
#define BOARD_SWCLK_PORT BOARD_GPIOA_BASE
#define BOARD_SWCLK_PIN  14U

#endif /* BOARD_IO_H */
